name: vennro

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./docker/server/nginx/data:/data
      - ./docker/server/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mariadb-public:/var/lib/mysql
      - ./docker/server/mariadb/config.cnf:/etc/mysql/conf.d/config.cnf
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin-container
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb-container
    volumes:
      - ./docker/server/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    networks:
      - proxy

  registry:
    image: registry:2
    container_name: registry-container
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./docker/server/registry/data:/var/lib/registry
      - ./docker/server/registry/auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Vennro Private Registry"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    networks:
      - proxy

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui-container
    restart: unless-stopped
    environment:
      - REGISTRY_URL=http://registry:5000
      - REGISTRY_AUTH=true
      - REGISTRY_TITLE=Vennro Private Registry
      - DELETE_IMAGES=true
    depends_on:
      - registry
    networks:
      - proxy

volumes:
  mariadb-public:

networks:
  proxy:
    external: true
